#define DEF				1
#define INTEGER			2
#define REAL			3
#define STRING			4
#define IF				5
#define THEN			6
#define WHILE			7
#define REAL_CONST		8
#define ID				9
#define INT_CONST		10
#define STRING_CONST	11
#define SEMI			12
#define COLON			13
#define LEFT_PAREN		14
#define RIGHT_PAREN		15
#define PLUS			16
#define MINUS			17
#define MULT			18
#define DIVIDE			19
#define CARAT			20
#define MOD				21
#define EQUAL			22
#define NOT_EQUAL		23
#define LESS_THAN		24
#define GREATER_THAN	25
#define LESS_EQUAL		26
#define GREATER_EQUAL	27
#define ASSIGN			28
#define LEFT_SQUARE		29
#define RIGHT_SQUARE	30
#define LEFT_BRACE		31
#define RIGHT_BRACE		32
#define COMMA			33
